<?php 
	//$asin = $this->_request->getParam('asin');
	//echo $asin;

?>
<br /><br />
<div id="view-content">
	<p>View script for controller <b>Games</b> and script/action name <b>index</b></p>
		<a href="<?= $this->url(array(
		'asin' => 'B00TG530M'),
		'games-asin-view'); ?>">Call of Duty 4: Modern Warfare</a>

	<p>Jason owns 14 games, and <?= $this->Gender("m"); ?> is currently playing Call of Duty: World at War.</p>
</div>